services:
  app.fe.ayni-webpage-landing:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: app.fe.ayni-webpage-landing

    restart: unless-stopped

    networks:
      - coolify

networks:
  coolify:
    external: true