services:
  app.fe.ayni-webpage-landing:
    labels:
      svc: "app.fe.ayni-webpage-landing"
    build:
      context: .
      dockerfile: Dockerfile

    container_name: app.fe.ayni-webpage-landing

    restart: unless-stopped
    ports:
      - "81:80"

    networks:
      - coolify

networks:
  coolify:
    external: true